### PR TITLE
Add Final Fantasy Tactics Advance 2: Grimoire of the Rift

### PR DESCRIPTION
**Pull request by silasary**

### CODE REVIEW

**Comment by Mysteryem** [comment]
`visualize_regions` is primarily a utility for developers, I doubt that should be called by default in `generate_output`.

Also, I hope the dev realises that each list concatenation `a + b` has to copy one of `a` or `b` and then extend/prepend the other because stuff like this is going to be making a lot of unnecessary intermediate copies. This is only run once during module initialisation, so it probably doesn't matter, but still.
```py
Weapons: typing.List[ItemData] = EquipKnives + EquipSwords + EquipBlades + EquipSabers + EquipKnightswords + \
                                 EquipRapiers + EquipGreatswords + EquipBroadswords + EquipKatanas + EquipSpears + \
                                 EquipRods + EquipStaves + EquipPoles + EquipKnuckles + EquipBows + EquipGreatbows + \
                                 EquipGuns + EquipInstruments + EquipHandcannons + EquipAxes + EquipHammers + \
                                 EquipMaces + EquipCards + EquipBooks
```

**Comment by Eijebong** [comment]
Concerns forwarded upstream https://discord.com/channels/731205301247803413/1296095764518277143/1323350964840697916 however I don't think they're a blocker

Let's do a double and see if I can r+ a PR with a comment or if CI will implode from it

/taskcluster r+

**Comment by Eijebong** [comment]
@silasary `[task 2024-12-30T18:06:17.751Z] Exception: The given apworld doesn't match the game named passed in. Expected Final Fantasy Tactics A2, got Final Fantasy Tactics A2: Grimoire of the Rift`

The name in the toml has to match the one in the apworld. If you thing the name displayed on the website should be different you can use `display_name` to override it (that's what I do with manuals)

**Comment by silasary** [comment]
Sorry, copied from the wrong place 😅
And I think dropping the subtitle is probably better for the website.  The game name is far too unwieldy if you include the whole thng

**Comment by Eijebong** [comment]
No problem, thanks for the PR, much appreciated :)

/taskcluster r+

**Pull request merged**
